# Generated by Django 5.0.2 on 2024-03-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_projectmanager_project_project_mangers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='mangers',
            new_name='managers',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
