# Generated by Django 5.0.2 on 2024-03-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_mangers_project_managers_employee_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='projects',
            field=models.ManyToManyField(blank=True, to='main.project', verbose_name='Projects'),
        ),
    ]
