# Generated by Django 5.0.2 on 2024-03-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_projectmanager_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmanager',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='projects',
        ),
        migrations.AddField(
            model_name='projectmanager',
            name='password',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
