# Generated by Django 5.0.2 on 2024-03-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_projectmanager_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='employees',
            field=models.ManyToManyField(blank=True, to='main.employee', verbose_name='Employees'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='password',
            field=models.CharField(max_length=120),
        ),
    ]
